name: CI for building C# projects

on:
  [push, workflow_dispatch]
  
defaults:
  run:
    working-directory: ./CSharp
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
   
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
        
      - name: Unit Test
        run: dotnet test --logger "trx;logfilename=${GITHUB_WORKSPACE}/unit_test_results.trx"

      - name: Test Reporter
        uses: dorny/test-reporter@v1.4.3
        if: always()
        with:
          name: publish test results

          path: "unit_test_results.trx"
          reporter: dotnet-trx
        
